### ISSUE TITLE
Running error coconut's code return the entire stack of tracebacks

### ISSUE THREAD

**Issue by mjenrungrot** [cs121-team-panda/coconut-interpreter-flask#21]
Need to return only traceback related to coconut's code.

```
Traceback (most recent call last):
  File "/home/circleci/project/tests/test_interpreter.py", line 88, in test_error
    assert ERR_OUTPUT in response.data
AssertionError

Stdout:
Finish compilation [5f1d2705-d2b3-4f34-84ee-b5bc1efaac56] to [5f1d2705-d2b3-4f34-84ee-b5bc1efaac56.py]
Error in running Coconut's code
Delete temp files 5f1d2705-d2b3-4f34-84ee-b5bc1efaac56 and 5f1d2705-d2b3-4f34-84ee-b5bc1efaac56.py
Output is
b'Traceback (most recent call last):\n  File "5f1d2705-d2b3-4f34-84ee-b5bc1efaac56.py", line 638, in <module>\n    1 + "a"\nTypeError: unsupported operand type(s) for +: \'int\' and \'str\'\n'
		
```

**Comment by nkadonaga** [comment]
😍
